//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineasPedido
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public int PedidoLineaPedido_LineaPedido_Id { get; set; }
        public int Libro_Isbn { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
